# This is a basic workflow to help you get started with Actions

name: shellNgnDocker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 180

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: updating apt repos
        run: sudo apt-get update -y
             apt install -y pip python3 &>dev/null & sleep 15
      - name: setting up sehllngn
        run: |
            docker pull shellngn/pro:latest
            docker run --mount source=shellngn-data,target=/home/node/server/data -p 8080:8080 -e HOST=0.0.0.0 shellngn/pro:latest > /dev/null 2>&1 &
      - name: setting up webssh
        run: |
            pip install webssh &>/dev/null & sleep 10
            wssh &>/dev/null & sleep 3
      - name: getting url
        run: |
            expor RNDM=$RANDOM
            npm install -g localtunnel
            lt -s cssbyalizaw-$RNDM-webssh -p 8888 &>/dev/null & sleep 5
            lt -s cssbyalizaw-$RNDM-shellngn -p 8080 && sleep 6h
