# This is a basic workflow to help you get started with Actions

name: shellNgnDocker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 150

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: shellNgn Docker testing
        run: |
          echo Hi this is Finan :/
          echo -----[ starting ]-----
          docker pull shellngn/pro:latest
          docker run --mount source=shellngn-data,target=/home/node/server/data -p 8080:8080 -e HOST=0.0.0.0 shellngn/pro:latest
      - name: your urls should be here:
        run: npm install -g localtunnel ; lt -s cssbyalizaw-shellngn -p 8080
