# This is a basic workflow to help you get started with Actions

name: simpleSSHng

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ngork_token:
        description: 'Yout Ngrok token : '
        required: true
      ngrok_port:
        description: ' port to forward | TCP '
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: primary configs
        run: |
          sudo apt update -y
          mkdir $HOME/logs
          sudo apt-get install python3 -y
          sudo apt-get install pip -y
          
      - name: user setting.
        run: |
          wget https://raw.githubusercontent.com/fennonina/ready-codes/main/CreatUser_f1ver
          chmod +x CreatUser_f1ver
          ./CreatUser_f1ver
      - name: setting up docker image
        run: | 
          docker pull shellngn/pro:latest && sleep 3
          sudo docker run -i -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest && sleep 2
      - name: setting up wshh.
        run: |
          sudo pip install webssh
      - name: setting up ngrok
        run: |
            wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
            gunzip ngrok-v3-stable-linux-amd64.tgz
            tar xf ngrok-v3-stable-linux-amd64.tar
            chmod +x ngrok
            ./ngrok config add-authtoken ${{ github.event.inputs.ngork_token }}
            ./ngrok tcp ${{ github.event.inputs.ngrok_port }}
      - name: keep running
        run: sleep 6h
        
        
