# This is a basic workflow to help you get started with Actions

name: poyoxy2

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      ngrok_token:
        description: 'your ngrok auth token'
        default: ''
        required: true
        type: string
      usrname:
        description: 'create a username , Example : f1ver'
        default: 'f1ver'
        required: false
        type: string
      passwrd:
        description: ' create a password for your user'
        required: true
        default: ''
        type: string


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo hello world!
          echo ${{ inputs.ngrok_token }}
          echo ${{ inputs.usrname }}
          echo ${{ inputs.passwrd }}
          echo successed
          
