# This is a basic workflow to help you get started with Actions

name: poyoxy2

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
      ngrok_token:
        description: 'your ngrok auth token'
        default: ''
        required: true
        type: string
      usrname:
        description: 'create a username , Example : f1ver'
        default: 'f1ver'
        required: false
        type: string
      passwrd:
        description: ' create a password for your user'
        required: true
        default: ''
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Vars priniting test
        run: |
          echo ----[ hello world! ]----
          echo The username is ${{ inputs.usrname }}
          echo The username is ${{ inputs.passwrd }}
          echo The username is ${{ inputs.ngrok_token }}
          echo The username is ${{ inputs.username }}
          echo ----[ successed ]-----
          
          
